_data/navigation.yml
Fix the yaml
because it's always yaml
=> fix: navigation

_data/toc.yml, _docs/framework-13.md, _docs/framework-16.md
Missing pics, will add pics in next PR.
=> feat: move framework instructions

_docs/ai.md
I lost 30 minutes trying to understand why `systemd --user start ollama` looked like it was hanging, when it fact it was pulling images... 🫠
Also I updated the ujust ollama commands in the doc.
=> Update doc for ollama

_docs/ai.md
Sorry for the double PR. After reading the doc again I realised I have half done it.
This PR reworks & updates the Ollama section so that it matches the current `ujust ollama` command.
Edit: spelling
=> Rework & update Ollama section

_docs/introduction.md
General enhancement and precision about
> *QWERTY* keyboard input and navigation
Also see https://github.com/ublue-os/config/pull/328
=> enhance: introduction secure boot

_data/toc.yml
=> lowercase d to fix 404

assets/css/main.css
If another text should be also edited, like note card text color or section text color, please let me know
Before:
After:
Before:
After:
=> chore: Increase contrast & text legibility in dark mode

.github/workflows/pages.yml, CNAME
- **fix: use npm on gh actions build**
- **fix(ci): workflow dispatch for docs deployment**
=> fix: workflow dispatch for pages

package-lock.json, package.json
Reverts ublue-os/bluefin-docs#61
=> Revert "chore(deps-dev): bump typescript from 5.6.3 to 5.7.2"

docs/FAQ.md, docs/introduction.md
It seems this is changed to `ujust rebase-helper.
I've also fixed Toolbx, which should be Toolbox + created a link to upstream.
=> Use ujust rebase-helper

docs/lts.md
Thunderbird installed just fine, remove it from differences
=> docs: update thunderbird ref for LTS

docs/lts.md
=> docs: fix info box syntax

docs/FAQ.md
Grammar and cladistic fixes, mainly.
=> Edit pass on the new "holding it wrong" FAQ item

docs/bluefin-gdx.md, docs/lts.md
Reverts ublue-os/bluefin-docs#115
=> revert: "feat: move lts to beta"

docs/bluefin-gdx.md, docs/lts.md
- **Reapply "feat: move lts to beta"**
This reverts commit 6bd477a6915602d9db8a6b1e933dcce4b39e9c11.
- **fix: gdx is also beta**
=> chore: put LTS and GDX as betas :)

docs/bluefin-gdx.md
We got these on https://github.com/ublue-os/bluefin-lts/pull/380
=> chore(gdx): mention VSCode cuda integrations as something we have now

docs/lts.md
Remove reference to hwe and update lts image description.
=> docs: Update lts.md

docs/administration.md
=> Update for F42

docs/contributing.md
Removed some extra backticks in code segments
=> typo: remove leftover backticks

docs/FAQ.md
Spotted a minor typo that was bugging me!
=> typo: FAQs.md

.github/workflows/pdf.yml
Makes gh CLI happier cuz then it knows what repo to operate on
=> ci(pdf): checkout git repo for gh cli

sidebars.ts
=> chore: make sidebar more fitting to project status

docs/gaming.md
This should fix the list being pretty hard to understand for the average user. 
Let me know if I should make any improvements (or grammer fixes).
=> Adding information about each gaming app and runtimes

docs/FAQ.md
Right now, language switch key is off, this documents how to turn it back on
=> Add FAQ regarding language switch key

docs/donations.md
Someone else has to be worthy of this in the last few months I'm sure!
=> Replace me with some new blood in the donation doc

docs/lts.md
=> typo: minor typo

docs/press-kit.md
`inapproprite` -> `inappropriate`
=> docs: minor typo fix

blog/2025-08-08-bluefin-on-lfx.md
Feel free to reject. These just make the latest post a little easier to read. <3
=> Fix: A few grammatical tweaks

docusaurus.config.ts
This'll prevent surprises to dark mode enjoyers 🙋
=> feat: respect `prefers-color-scheme`

.github/workflows/sync-bluefin-releases.yml
=> revert: move back to old changelog syncer

src/components/FeedItems.module.css, src/components/FeedItems.tsx
=> chore: fix styling and format of changelog cards

blog/2025-09-17-color-with-bluefin.md, blog/color-with-bluefin.pdf
Added a new PDF document titled 'Color with Bluefin' with details and a download link.
=> Add 'Color with Bluefin' PDF announcement
